version: '3.8'

services:
  scripts:
    container_name: my_python
    build: .
    environment:
      DB_URL: mongodb://database/HelloWorld
    depends_on:
      - database
  database: 
    container_name: my_mongo
    image: mongo:4.0-xenial
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - HelloWorldDB:/data/db

volumes:
  HelloWorldDB: